version: "3"
services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_USER: root
      MYSQL_PASSWORD: 1234
      MYSQL_DATABASE: demo
    ports:
      - 3306:3306
    networks:
      - backend_network
  shopping:
    image: juicelee/shopping:${TAG:-latest}
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/demo
      SRPING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 1234
    ports:
      - 8080:8080
    build: .
    restart: always
    links:
      - db
    depends_on:
      - db
    networks:
      - backend_network
networks:
  backend_network: