# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:8-jdk
        environment:
          DB_ROOT_USER: root
          DB_URL: jdbc:mysql://localhost:3306/demo
          DB_DRIVER: com.mysql.cj.jdbc.Driver
          DB_PASS: 1234
      - image: circleci/mysql:latest
        environment:
          MYSQL_ROOT_PASSWORD: 1234


      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/demo

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout

      - run:
          name: Login to DockerHub
          command: docker login -u $DOCKER_USER -p $DOCKER_PASS

      - run:
          name: Run DB
          command: dockerize -wait tcp://localhost:3306 -timeout 1m

      - run:
          name: install MYSQL CLI
          command: sudo apt-get install mysql-client

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: gradle dependencies

      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}

      # run tests!
      - run: gradle test --stacktrace
