# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:8-jdk
        environment:
          DB_ROOT_USER: root
          DB_URL: jdbc:mysql://docker-mysql:3306/demo
          DB_DRIVER: com.mysql.cj.jdbc.Driver
          DB_PASS: 1234
      - image: circleci/mysql:latest
        command: [--default-authentication-plugin=mysql_native_password]
        environment:
          MYSQL_ROOT_PASSWORD: 1234


      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/Samsung_ToyProject

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout

      - run:
          name: Login to DockerHub
          command: docker login -u $DOCKER_USER -p $DOCKER_PASS

      - run:
          name: Run DB
          command: dockerize -wait tcp://localhost:3306 -timeout 1m

      - run:
          name: install MYSQL CLI
          command: sudo apt-get update
                  && sudo apt-get install default-mysql-client
      - run:
          name: create Demo DB
          command: mysql -h 127.0.0.1 -u root < ~/Samsung_ToyProject/schema/add_database.sql

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: gradle dependencies

      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}

      - run:
          command: |
            MYSQL_ADDR="localhost"
            echo $MYSQL_ADDR

      - run: gradle test

      - run:
          command: |
            MYSQL_ADDR="docker-mysql"
            echo $MYSQL_ADDR

      - run: gradle bootJar

      - setup_remote_docker:
          version: 20.10.6

      - run:
          name: Build docker image
          command: docker-compose build

      - run:
          name: Deploy docker image
          command: docker push juicelee/shopping:latest


